name: Execute Scala Steward

on:
  # Triggers the workflow on push events but only for the main branch.
  push:
    branches: [ main ]
  # Schedules the workflow to run 4 times daily
  schedule:
    - cron: '0 0/4 * * *'
  # Allows the workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64

      - name: Set up GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.SIGNING_KEY }}
          git_commit_gpgsign: true

      - name: Execute Scala Steward
        uses: arashi01/scala-steward-action@74ec7e2e31a572d8d5233a6c8af0c8e3ff20dcc4
        with:
          github-token: ${{ secrets.STEWARD_TOKEN }}
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name: 'Zantekk Dev Bot'
          repos-file: 'repositories.md'
          sign-commits: true
          signing-key: ${{ secrets.SIGNING_KEY_ID }}
          do-not-fork: false
