name: Execute Scala Steward

on:
  # Triggers the workflow on push events but only for the main branch.
  push:
    branches: [ main ]
  # Schedules the workflow to run 3 times daily
  schedule:
    - cron: '0 6 * * *'
  # Allows the workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  scala-steward:

    runs-on: ubuntu-latest

    env:
      SCALA_STEWARD_WORKSPACE: '${{ github.workspace }}/scala-steward-workspace'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          architecture: x64
          check-latest: true

      - name: Scala Steward Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.SCALA_STEWARD_WORKSPACE }}
          key: '${{ runner.os }}-scala-steward-app-workspace'
            
      - name: Execute Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-app-id: ${{ secrets.SCALA_STEWARD_APP_ID }}
          github-app-installation-id: ${{ secrets.SCALA_STEWARD_APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_KEY }}
          other-args: '--workspace ${{ env.SCALA_STEWARD_WORKSPACE }}'
