name: Execute Scala Steward

on:
  # Triggers the workflow on push events but only for the main branch.
  push:
    branches: [ main ]
  # Schedules the workflow to run 3 times daily
  schedule:
    - cron: '0 0/8 * * *'
  # Allows the workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          architecture: x64
          check-latest: true

      - name: Set up GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.OSS_PUBLISH_USER_SIGNING_KEY }}
          git_commit_gpgsign: true

      - name: Execute Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.OSS_TEAM_TOKEN }}
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name: 'Shuwari Africa Team'
          repos-file: 'repositories.md'
          sign-commits: true
          signing-key: ${{ secrets.OSS_PUBLISH_USER_SIGNING_KEY_ID }}
